In [11]:
import numpy as np

In [12]:
# Factorización LU
def lu_factorization(A):
  n = A.shape[0]
  L = np.identity(n)
  U = np.copy(A)

  for i in range(n):
    for j in range(i + 1, n):
      if U[i, i] == 0:
        return None

      factor = U[j, i] / U[i, i]
      L[j, i] = factor
      U[j, :] = U[j, :] - factor * U[i, :]

  return L, U

In [13]:
def solve_linear_system(A, b):
  L, U = lu_factorization(A) # Llamada a la función LU
  if L is None or U is None:
    return None

  n = len(b) # Dimensión del vector b
  y = np.zeros(n) # Inicializa vector y
  x = np.zeros(n) # Inicializa vector x

  # Resolver Ly = b con sustitución hacia delante
  for i in range(n):
    y[i] = b[i]
    for j in range(i):
      y[i] -= L[i, j] * y[j]

  # Resolver Ux = y con sustitución hacia atrás
  for i in range(n - 1, -1, -1):
    x[i] = y[i]
    for j in range(i + 1, n):
      x[i] -= U[i, j] * x[j]
    x[i] /= U[i, i]

  return x # Retorno de la solución

In [19]:
# Ejercicio 7 literal a
A = np.array([[2, -1, 1],
              [3, 3, 9],
              [3, 3, 5]])
b = np.array([-1, 0, 4])

x = solve_linear_system(A, b)

if x is not None:
  print("Solución del sistema lineal:")
  print(x)

  L, U = lu_factorization(A)
  print("\nMatriz triangular inferior L:")
  print(L)
  print("\nMatriz triangular superior U:")
  print(U)
else:
  print("Falló la factorización LU (posible división por cero).")


Solución del sistema lineal:
[ 1.0625  2.125  -1.    ]

Matriz triangular inferior L:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]

Matriz triangular superior U:
[[ 2 -1  1]
 [ 0  4  7]
 [ 0  0 -4]]


In [15]:
# Ejercicio 7 literal b
A = np.array([[1.012, -2.132, 3.104],
              [-2.132, 4.096, -7.013],
              [3.104, -7.013, 0.014]])
b = np.array([1.984, -5.049, -3.895])

x = solve_linear_system(A, b)

if x is not None:
  print("Solución del sistema lineal:")
  print(x)

  L, U = lu_factorization(A)
  print("\nMatriz triangular inferior L:")
  print(L)
  print("\nMatriz triangular superior U:")
  print(U)
else:
  print("Falló la factorización LU (posible división por cero).")

Solución del sistema lineal:
[1. 1. 1.]

Matriz triangular inferior L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]

Matriz triangular superior U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


In [17]:
# Ejercicio 7 literal c
A = np.array([[2, 0, 0, 0],
              [1, 1.5, 0, 0],
              [0, -3, 0.5, 0],
              [2, -2, 1, 1]])
b = np.array([3, 4.5, -6.6, 0.8])

x = solve_linear_system(A, b)

if x is not None:
  print("Solución del sistema lineal:")
  print(x)

  L, U = lu_factorization(A)
  print("\nMatriz triangular inferior L:")
  print(L)
  print("\nMatriz triangular superior U:")
  print(U)
else:
  print("Falló la factorización LU (posible división por cero).")

Solución del sistema lineal:
[ 1.5  2.  -1.2  3. ]

Matriz triangular inferior L:
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]

Matriz triangular superior U:
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]


In [18]:
# Ejercicio 7 literal d
A = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
              [-4.0231, 6.0000, 0, 1.1973],
              [-1.0000, -5.2107, 1.1111, 0],
              [6.0235, 7.0000, 0, -4.1561]])
b = np.array([17.102, -6.1593, 3.0004, 0.0000])

x = solve_linear_system(A, b)

if x is not None:
  print("Solución del sistema lineal:")
  print(x)

  L, U = lu_factorization(A)
  print("\nMatriz triangular inferior L:")
  print(L)
  print("\nMatriz triangular superior U:")
  print(U)
else:
  print("Falló la factorización LU (posible división por cero).")

Solución del sistema lineal:
[2.9398512  0.0706777  5.67773512 4.37981223]

Matriz triangular inferior L:
[[ 1.          0.          0.          0.        ]
 [-1.84919103  1.          0.          0.        ]
 [-0.45964332 -0.25012194  1.          0.        ]
 [ 2.76866152 -0.30794361 -5.35228302  1.        ]]

Matriz triangular superior U:
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  2.37689114e-15  0.00000000e+00  1.20361280e+01]]
