In [1]:
import numpy as np

def lu_factorization(A):

  n = A.shape[0] # Obtiene el número de filas/columnas
  L = np.identity(n) # Matriz identidad de tamaño nxn
  U = np.copy(A) # Copia de la matriz original

  for i in range(n):
    for j in range(i + 1, n):
      if U[i, i] == 0:
        # Factorización falla si el elemento de la diagonal principal es cero
          return None

      factor = U[j, i] / U[i, i] # Factor de escalado
      L[j, i] = factor
      U[j, :] = U[j, :] - factor * U[i, :]

  return L, U

In [2]:
# Ejercicio 6 literal a
A = np.array([[2, -1, 1],
              [3, 3, 9],
              [3, 3, 5]])

L, U = lu_factorization(A)

if L is not None and U is not None:
  print("Matriz A:")
  print(A)
  print("\nMatriz triangular inferior L:")
  print(L)
  print("\nMatriz triangular superior U:")
  print(U)
  print("\nLU (Verificación):")
  print(np.dot(L,U))
else:
  print("Falló factorización LU (division by zero).")

Matriz A:
[[ 2 -1  1]
 [ 3  3  9]
 [ 3  3  5]]

Matriz triangular inferior L:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]

Matriz triangular superior U:
[[ 2 -1  1]
 [ 0  4  7]
 [ 0  0 -4]]

LU (Verificación):
[[ 2.  -1.   1. ]
 [ 3.   2.5  8.5]
 [ 3.   2.5  4.5]]


In [3]:
# Ejercicio 6 literal b
B = np.array([[1.012, -2.132, 3.104],
              [-2.132, 4.096, -7.013],
              [3.104, -7.013, 0.014]])

L, U = lu_factorization(B)

if L is not None and U is not None:
  print("Matriz B:")
  print(B)
  print("\nMatriz triangular inferior L:")
  print(L)
  print("\nMatriz triangular superior U:")
  print(U)
  print("\nLU (Verificación):")
  print(np.dot(L,U))
else:
  print("Falló factorización LU (division by zero).")

Matriz B:
[[ 1.012 -2.132  3.104]
 [-2.132  4.096 -7.013]
 [ 3.104 -7.013  0.014]]

Matriz triangular inferior L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]

Matriz triangular superior U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]

LU (Verificación):
[[ 1.012 -2.132  3.104]
 [-2.132  4.096 -7.013]
 [ 3.104 -7.013  0.014]]


In [4]:
# Ejercicio 6 literal c
C = np.array([[2, 0, 0, 0],
              [1, 1.5, 0, 0],
              [0, -3, 0.5, 0],
              [2, -2, 1, 1]])

L, U = lu_factorization(C)

if L is not None and U is not None:
  print("Matriz C:")
  print(C)
  print("\nMatriz triangular inferior L:")
  print(L)
  print("\nMatriz triangular superior U:")
  print(U)
  print("\nLU (Verificación):")
  print(np.dot(L,U))
else:
  print("Falló factorización LU (division by zero).")

Matriz C:
[[ 2.   0.   0.   0. ]
 [ 1.   1.5  0.   0. ]
 [ 0.  -3.   0.5  0. ]
 [ 2.  -2.   1.   1. ]]

Matriz triangular inferior L:
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]

Matriz triangular superior U:
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]

LU (Verificación):
[[ 2.   0.   0.   0. ]
 [ 1.   1.5  0.   0. ]
 [ 0.  -3.   0.5  0. ]
 [ 2.  -2.   1.   1. ]]


In [5]:
# Ejercicio 6 literal d
D = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
              [-4.0231, 6.0000, 0, 1.1973],
              [-1.0000, -5.2107, 1.1111, 0],
              [6.0235, 7.0000, 0, -4.1561]])

L, U = lu_factorization(D)

if L is not None and U is not None:
  print("Matriz D:")
  print(D)
  print("\nMatriz triangular inferior L:")
  print(L)
  print("\nMatriz triangular superior U:")
  print(U)
  print("\nLU (Verificación):")
  print(np.dot(L,U))
else:
  print("Falló factorización LU (division by zero).")

Matriz D:
[[ 2.1756  4.0231 -2.1732  5.1967]
 [-4.0231  6.      0.      1.1973]
 [-1.     -5.2107  1.1111  0.    ]
 [ 6.0235  7.      0.     -4.1561]]

Matriz triangular inferior L:
[[ 1.          0.          0.          0.        ]
 [-1.84919103  1.          0.          0.        ]
 [-0.45964332 -0.25012194  1.          0.        ]
 [ 2.76866152 -0.30794361 -5.35228302  1.        ]]

Matriz triangular superior U:
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  2.37689114e-15  0.00000000e+00  1.20361280e+01]]

LU (Verificación):
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [-4.02310000e+00  6.00000000e+00  0.00000000e+00  1.19730000e+00]
 [-1.00000000e+00 -5.21070000e+00  1.11110000e+00  0.00000000e+00]
 [ 6.02350000e+00  7.00000000e+00 -3.69327004e-16 -4.15610000e+00]]
